# Persistent Webuzo include:
# /var/webuzo-data/apache2/custom/domains/emsindia.com.conf
#
# This file is included inside both emsindia.com VirtualHost blocks by
# /usr/local/apps/apache2/etc/conf.d/webuzoVH.conf.

ProxyPreserveHost On
ProxyRequests Off

ProxyPass "/share/" "http://127.0.0.1:30000/api/v1/user/share/"
ProxyPassReverse "/share/" "http://127.0.0.1:30000/api/v1/user/share/"

ProxyPass "/uploads/" "http://127.0.0.1:30000/uploads/"
ProxyPassReverse "/uploads/" "http://127.0.0.1:30000/uploads/"
